Article.create(title: "This Is Not An Article", body: "Neutra glossier small batch, four loko fam portland chia butcher tilde occupy bicycle rights live-edge. Copper mug marfa gentrify, pabst art party everyday carry banjo snackwave craft beer trust fund butcher organic ethical poke. Kitsch ethical ramps, kinfolk asymmetrical af glossier tattooed tofu helvetica pok pok thundercats paleo before they sold out. Crucifix bicycle rights kinfolk kale chips, truffaut raclette vinyl banh mi keffiyeh pok pok fanny pack neutra jianbing taxidermy. Vexillologist mustache taiyaki lyft, lumbersexual hashtag deep v tumeric man bun. Cray williamsburg vexillologist church-key. Chartreuse selvage synth fashion axe humblebrag.

Letterpress tattooed subway tile la croix, 90's fanny pack slow-carb. Ugh mustache selfies jianbing chicharrones, freegan post-ironic green juice. Chillwave readymade retro, selfies hella hashtag copper mug ugh. Farm-to-table YOLO etsy selvage tote bag. Shabby chic chartreuse snackwave, vape cray coloring book mixtape venmo normcore street art thundercats VHS. Butcher flannel celiac kitsch tacos lo-fi woke kale chips bicycle rights, lumbersexual squid letterpress shaman. Affogato occupy sustainable tattooed, XOXO poutine tumeric fixie umami locavore succulents.

Craft beer food truck swag af. Banh mi shabby chic art party, quinoa shoreditch pickled slow-carb tattooed DIY mumblecore enamel pin selfies venmo twee knausgaard. Raw denim keytar polaroid authentic austin distillery, post-ironic tumblr coloring book thundercats snackwave vegan pickled retro ennui. Etsy iceland tattooed lyft sriracha, listicle letterpress poke fingerstache photo booth adaptogen kogi. Four dollar toast 90's glossier vegan. Tote bag raclette gentrify jianbing pitchfork pour-over. Plaid glossier portland celiac banh mi flexitarian.

Cray before they sold out keytar, edison bulb artisan single-origin coffee 90's umami craft beer freegan tbh cardigan polaroid bespoke. La croix mixtape locavore mumblecore, cloud bread craft beer woke ugh. Freegan lomo polaroid celiac vice fanny pack. Viral asymmetrical yr, blue bottle green juice yuccie tofu taiyaki pinterest tumeric subway tile sustainable flannel. Chillwave pug umami cornhole, freegan master cleanse dreamcatcher. Raclette PBR&B bushwick aesthetic, marfa craft beer butcher mlkshk kombucha cronut cardigan disrupt you probably haven't heard of them schlitz. Marfa hammock neutra kale chips.", user_id: 3)

Article.create(title: "10 Crazy Reasons Journalism is Dying", body: "Enamel pin tacos cold-pressed hella kogi bespoke. Godard +1 poke, pug listicle food truck celiac portland shoreditch hashtag hella cornhole art party prism bicycle rights. Cold-pressed butcher intelligentsia, activated charcoal green juice poutine yr kickstarter next level iPhone. Scenester activated charcoal hoodie, locavore occupy seitan retro enamel pin marfa pinterest. Coloring book twee ethical chia polaroid. Vinyl disrupt kogi, skateboard lyft truffaut cloud bread. DIY subway tile asymmetrical raw denim.

Normcore shaman intelligentsia VHS, photo booth brooklyn bushwick direct trade gluten-free. Wayfarers brooklyn raw denim hell of, art party affogato vegan asymmetrical yr succulents kombucha fashion axe try-hard taiyaki. Art party pinterest succulents bicycle rights, chambray small batch glossier gastropub tote bag locavore tumblr heirloom crucifix. Unicorn activated charcoal kombucha, hashtag tbh deep v fam edison bulb helvetica tattooed. Trust fund disrupt you probably haven't heard of them, cronut raclette bicycle rights humblebrag narwhal. Whatever jianbing glossier hammock, banjo gluten-free offal pug. Jean shorts subway tile readymade, narwhal coloring book mumblecore mustache VHS viral af.

Four loko vaporware waistcoat leggings skateboard poutine. Ugh lomo cardigan paleo, cliche everyday carry portland fixie freegan vape shaman. Before they sold out master cleanse typewriter, irony pop-up vice dreamcatcher cloud bread austin keffiyeh deep v snackwave. Beard bushwick williamsburg, gastropub deep v freegan af air plant prism subway tile typewriter dreamcatcher microdosing fam. Umami put a bird on it williamsburg kickstarter. Cloud bread health goth kinfolk shabby chic af farm-to-table, cred asymmetrical microdosing forage taxidermy. Pok pok ramps jianbing, keytar wayfarers microdosing celiac hammock fam artisan taiyaki cray asymmetrical.", user_id: 2)
